-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 16:45:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eparkingrx_accounts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eparkingrx_accounts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eparkingrx_accounts` DEFAULT CHARACTER SET utf8 ;
USE `eparkingrx_accounts` ;

-- -----------------------------------------------------
-- Table `eparkingrx_accounts`.`Login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eparkingrx_accounts`.`Login` ;

CREATE TABLE IF NOT EXISTS `eparkingrx_accounts`.`Login` (
  `LoginId` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LoginId`),
  UNIQUE INDEX `LoginId_UNIQUE` (`LoginId` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eparkingrx_accounts`.`Vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eparkingrx_accounts`.`Vehicle` ;

CREATE TABLE IF NOT EXISTS `eparkingrx_accounts`.`Vehicle` (
  `VehicleId` INT NOT NULL AUTO_INCREMENT,
  `RegistrationNumber` VARCHAR(45) NOT NULL,
  `VinNumber` VARCHAR(45) NOT NULL,
  `Brand` VARCHAR(45) NULL,
  `Model` VARCHAR(45) NULL,
  `ProductionYear` VARCHAR(4) NULL,
  PRIMARY KEY (`VehicleId`),
  UNIQUE INDEX `VehicleId_UNIQUE` (`VehicleId` ASC) VISIBLE,
  UNIQUE INDEX `RegistrationNumber_UNIQUE` (`RegistrationNumber` ASC) VISIBLE,
  UNIQUE INDEX `VinNumber_UNIQUE` (`VinNumber` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eparkingrx_accounts`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eparkingrx_accounts`.`Client` ;

CREATE TABLE IF NOT EXISTS `eparkingrx_accounts`.`Client` (
  `ClientId` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PESEL` VARCHAR(11) NOT NULL,
  `Login_LoginId` INT NOT NULL,
  `Vehicle_VehicleId` INT NOT NULL,
  PRIMARY KEY (`ClientId`),
  UNIQUE INDEX `ClientId_UNIQUE` (`ClientId` ASC) VISIBLE,
  INDEX `fk_Client_Login_idx` (`Login_LoginId` ASC) VISIBLE,
  INDEX `fk_Client_Vehicle1_idx` (`Vehicle_VehicleId` ASC) VISIBLE,
  UNIQUE INDEX `Login_LoginId_UNIQUE` (`Login_LoginId` ASC) VISIBLE,
  UNIQUE INDEX `Vehicle_VehicleId_UNIQUE` (`Vehicle_VehicleId` ASC) VISIBLE,
  UNIQUE INDEX `PESEL_UNIQUE` (`PESEL` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Login`
    FOREIGN KEY (`Login_LoginId`)
    REFERENCES `eparkingrx_accounts`.`Login` (`LoginId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Vehicle1`
    FOREIGN KEY (`Vehicle_VehicleId`)
    REFERENCES `eparkingrx_accounts`.`Vehicle` (`VehicleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eparkingrx_accounts`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eparkingrx_accounts`.`Account` ;

CREATE TABLE IF NOT EXISTS `eparkingrx_accounts`.`Account` (
  `AccountId` INT NOT NULL AUTO_INCREMENT,
  `AccountAmount` DECIMAL(5,2) NOT NULL,
  `Client_ClientId` INT NOT NULL,
  PRIMARY KEY (`AccountId`),
  UNIQUE INDEX `AccountId_UNIQUE` (`AccountId` ASC) VISIBLE,
  INDEX `fk_Account_Client1_idx` (`Client_ClientId` ASC) VISIBLE,
  UNIQUE INDEX `Client_ClientId_UNIQUE` (`Client_ClientId` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Client1`
    FOREIGN KEY (`Client_ClientId`)
    REFERENCES `eparkingrx_accounts`.`Client` (`ClientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
